version: '3.8'

services:
  web:
    build: .
    command: flask run --host=0.0.0.0 --port=5000
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - worker

  redis:
    image: "redis:alpine"

  worker:
    build: .
    command: sh -c "celery -A app.celery worker --loglevel=info -c 2"
    volumes:
      - .:/app
    depends_on:
      - redis
